#server:
#  port: 12345

spring:
  config:
    import: application-db.yml

# mybatis 관련 설정
mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: classpath:mapper/*.xml

### log level setting ###
logging:
  level:
    root: info